name: diario_de_entrenamiento_demo
description: "Diario de entrenamiento inteligente."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # --- Dependencias del MVP ---
  hive: ^2.2.3           # Base de datos NoSQL local
  hive_flutter: ^1.1.0   # Integración de Hive con Flutter
  path_provider: ^2.1.1 # Para obtener directorios del sistema (donde guardar Hive)
  image_picker: ^1.0.4    # Para seleccionar videos de la galería
  video_player: ^2.10.0 # Reproducción de videos
  permission_handler: ^11.0.1 # Para solicitar permisos (galería)
  provider: ^6.0.5       # Gestión del estado
  intl: ^0.18.0          # Internacionalización y formato de fecha
  video_player_win: ^3.2.0
  flutter_speed_dial: ^7.0.0
  video_thumbnail: ^0.5.6
  shared_preferences: ^2.5.3
  # --------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # --- Dependencias de Desarrollo para Hive ---
  hive_generator: ^2.0.1 # Generador de código para Hive
  build_runner: ^2.4.6   # Para ejecutar generadores de código
  # --------------------------------------------
flutter:
  uses-material-design: true
